#ifndef SKINWIDGET_GLOBAL_H
#define SKINWIDGET_GLOBAL_H

#if defined(SKINWIDGET_LIBRARY)
#  define SKINWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SKINWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif


#endif // SKINWIDGET_GLOBAL_H
