######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 28 14:13:45 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += toydialog.h
FORMS += toydialog.ui
SOURCES += main.cpp toydialog.cpp
