######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 28 14:13:45 2018
######################################################################
QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET =  pop
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += toydialog.h

SOURCES += \
		    main.cpp\
		    toydialog.cpp

FORMS += toydialog.ui
